name: pyjive-full
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - jupyterlab=3.4.8
  - matplotlib=3.5.2
  - numpy=1.22.3
  - pandas=1.5.1
  - pip=22.1.2
  - pyqtwebengine=5.15.4
  - pytest=7.1.2
  - pyvista=0.36.1
  - scipy=1.8.1
  - seaborn=0.12.0
  - spyder=5.2.2
  - pip:
    - pygmsh==7.1.17
    - sympy==1.11
